### ISSUE TITLE
Implement I'm a Teapot

### ISSUE THREAD

**Issue by yannikinniger** [BaselHack2021/api#1]
Because we all love Teapots a new Endpoint to return 418 I'm a Teapot is needed. We don't like coffee therefor we need to drink more tea: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418

**Comment by 1H0** [comment]
LGTM @michaelbeutler @yannikinniger

**Comment by michaelbeutler** [comment]
Fixed!

**Comment by yannikinniger** [comment]
Please use 418 HTTP code

**Comment by 1H0** [comment]
LGTM now
